### ISSUE TITLE
create a new map

### ISSUE THREAD

**Issue by DarrenWong** [Jasonnor/Car-Simulator#1]
Hey, the simulator is cool and I want to create some new map for research use.
Can I got the meaning of the coordinate[4] and coordinate[5] in the map definition?  something like 0,1 or -1 0

```
var map1 = [
        [-6, -13, 6, -13, 0, 1],
        [-6, -13, -6, 22, -1, 0],
        [-6, 22, 18, 22, 0, 1],
        [18, 22, 18, 50, -1, 0],
        [18, 50, 30, 50, 0, -1],
        [6, -13, 6, 10, 1, 0],
        [6, 10, 30, 10, 0, -1],
        [30, 10, 30, 50, 1, 0]
    ],
```

The map I try to create, corner is not so good, I think not setting proper data of last two words
```
var map4 = [
        [-15, -15, 65, -15, 0, 1],
        [-15, -15,-15, 65, -1, 0],
        [-15, 65, 65, 65,0,1],
        [65, 65, 65, -15, -1, 0],
        [0, 0, 0, 20, 0, 0],
        [0, 0, 50, 0, 1, 0],
        [0, 20, 50, 20, 0, -1],
        [50, 0, 50, 20, 1, 0],
        [0, 20, 30, 20, 0, -1],
        [0, 35, 0, 50, 1, 0],
        [0, 35, 50, 35, 0, -1],
        [0, 50, 50, 50, 1, 0],
        [50,50, 50, 35, 0, -1]
  
    ],
```
![image](https://user-images.githubusercontent.com/5771106/39998777-b7d3a4e8-57b9-11e8-8671-24f5aed66939.png)

**Comment by Jasonnor** [comment]
Hi, coordinate[4] and coordinate[5] is offset of wall generated direction.
If wall is vertical direction, coordinate[4] will be 1 or -1 otherwise 0.
If wall is horizontal direction, coordinate[5] will be 1 or -1 otherwise 0.
Which 1 or -1 means wall generated by right or left in coordinate[4], and generated by top or down in coordinate[5].

I think there is something wrong with my map drawing code 😅, so it will be a bit trickier to understand.
You can try to reverse 1 or -1 if there is a problem with the corner.

**Comment by DarrenWong** [comment]
got it and thank you. So -1 or 1 or 0 are random based ? or we can calculate then somewhere we might use -1, other part use -1 or 0.
